name       : freeimage
version    : 3.18.0
release    : 3
source     :
    - https://netcologne.dl.sourceforge.net/project/freeimage/Source%20Distribution/3.18.0/FreeImage3180.zip : f41379682f9ada94ea7b34fe86bf9ee00935a3147be41b6569c9605a53e438fd
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : Library to support graphics image formats.
description: |
    FreeImage is a library project for developers who would like to support popular graphics image formats (PNG, JPEG, TIFF, BMP and others).
libsplit   : no
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(libjpeg)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libraw_r)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - dos2unix
    - jxrlib-devel
setup      : |
    # This comes from Fedora
    # https://src.fedoraproject.org/rpms/freeimage/blob/fc41dd11c6506ce4b5372a61c7ac41263e25c5f9/f/freeimage.spec#_67
    %patch -p1 < $pkgfiles/FreeImage_unbundle.patch
    rm -r Source/Lib* Source/ZLib Source/OpenEXR
    > Source/FreeImage/PluginG3.cpp
    > Source/FreeImageToolkit/JPEGTransform.cpp

    sh gensrclist.sh
    %make -f Makefile.gnu dos2unix
    sh genfipsrclist.sh
    %make -f Makefile.fip dos2unix
build      : |
    %make -f Makefile.gnu
    %make -f Makefile.fip
install    : |
    %make_install -f Makefile.gnu
    %make_install -f Makefile.fip
